version: "3"
services:
  db:
    image: mysql:latest
    container_name: mysql-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: jpa_ex
      MYSQL_PASSWORD: root1234
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root1234
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)